# This is a basic workflow to help you get started with Actions

name: Build OS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
    # branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Build 
        run: |
          wget https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh -O brew-install.sh
          ls -al
          chmod +x ./brew-install.sh
          CI=1 ./brew-install.sh
          rm ./brew-install.sh
          sudo apt-get install build-essential -y
          echo >> /home/runner/.bashrc
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/runner/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install gmp
          brew install mpfr
          brew install nasm
          brew install libmpc
          brew install gcc
          echo installing gcc cross compiler
          cd ~/work/NuggetOS/NuggetOS
          ls -al
          ls -al
          ls -al /usr/bin/gcc-*
          whereis gcc-14
          export CC=/home/linuxbrew/.linuxbrew/bin/gcc-14
          export LD=/home/linuxbrew/.linuxbrew/bin/gcc-14
          export PREFIX="/usr/local/i386elfgcc"
          export TARGET=i386-elf
          export PATH="$PREFIX/bin:$PATH"
          mkdir /tmp/src
          cd /tmp/src
          curl -O https://ftp.gnu.org/gnu/binutils/binutils-2.43.tar.gz
          tar xf binutils-2.43.tar.gz
          mkdir binutils-build
          cd binutils-build
          sudo ../binutils-2.43/configure --target=i386-elf --enable-interwork --enable-multilib --disable-nls --disable-werror --prefix="/usr/local/i386elfgcc" 2>&1 | tee configure.log
          sudo make all install 2>&1 | tee make.log
          cd /tmp/src/
          curl -O https://ftp.gnu.org/gnu/gcc/gcc-14.2.0/gcc-14.2.0.tar.gz
          tar xf ./gcc-14.2.0.tar.gz
          mkdir gcc-build
          cd gcc-build
          cd ../gcc-14.2.0
          sudo ./contrib/download_prerequisites
          cd ../gcc-build
          sudo ../gcc-14.2.0/configure --target=i386-elf --prefix="/usr/local/i386elfgcc" --disable-nls --disable-libssp --enable-languages=c --without-headers
          sudo make all-gcc
          sudo make all-target-libgcc
          sudo make install-gcc
          sudo make install-target-libgcc
          ls /home/linuxbrew/.linuxbrew/bin/
          echo ls and lscpu
          echo ls i386elfgcc
          ls -al /usr/local/
          ls -al /usr/local/i386elfgcc
          lscpu
          cd ~/work/NuggetOS/NuggetOS/
          ls -al
          echo i386-elf-gcc version info
          /usr/local/i386elfgcc/bin/i386-elf-gcc --version
          /usr/local/i386elfgcc/bin/i386-elf-gcc -ffreestanding -c ./src/kernel/kernel.c -o ./kernel.o
          nasm ./src/boot/kernel_entry.asm -f elf -o kernel_entry.o
          /usr/local/i386elfgcc/bin/i386-elf-ld -o ./kernel.bin -Ttext 0x1000 ./kernel_entry.o ./kernel.o --oformat binary
          nasm ./src/boot/bootsect.asm -f bin -o ./bootsect.bin
          cat bootsect.bin kernel.bin > os-image.bin
          echo df
          df -h
          echo lsblk
          lsblk
      - uses: actions/upload-artifact@v4
        with:
          name: os-image.bin
          path: ./os-image.bin
